version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd backend 
      - npm install
      - cd ../frontend
      - npm install
  build:
    commands:
      - echo Building React frontend...
      - npm run build 
      - echo Copying frontend build to backend public directory...
      - mkdir -p ../backend/public
      - cp -r dist ../backend/public
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...
      - cd ../backend
      - cp ../appspec.yml .
      - cp -r ../scripts .

artifacts:
  files:
    - "**/*"
  base-directory: backend
