version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm install
      - cd ../frontend
      - npm install

  build:
    commands:
      - echo Building React frontend...
      - npm run build
      - echo Copying frontend build to backend public/dist directory...
      - rm -rf ../backend/public/dist
      - mkdir -p ../backend/public/dist
      - cp -r dist/* ../backend/public/dist/

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...
      - cd ../backend
      - cp ../appspec.yml .
      - cp -r ../scripts .
artifacts:
  files:
    - "**/*"
  base-directory: backend
