apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: varun029/kbf_backend:01
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: FRONTEND_URL
            - name: BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: BACKEND_URL
            - name: BACKEND_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: BACKEND_PORT
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: NODE_ENV
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
